# Generated by Django 5.2.3 on 2025-11-21 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary'), ('internship', 'Internship'), ('parttime', 'Part-time')], default='permanent', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('renewed', 'Renewed'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='hr.employee')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractRenewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renew_date', models.DateField()),
                ('old_end_date', models.DateField()),
                ('new_end_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renew_logs', to='hr.employeecontract')),
            ],
            options={
                'ordering': ['-renew_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='employeecontract',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='contract_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='contractrenewlog',
            constraint=models.CheckConstraint(condition=models.Q(('new_end_date__gt', models.F('old_end_date'))), name='renew_end_after_old'),
        ),
    ]
