# Generated by Django 5.2.3 on 2025-11-21 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employeecontract_contractrenewlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_overnight', models.BooleanField(default=False, help_text='إذا كان الشفت يبدأ في يوم وينتهي في اليوم التالي (مثل 22:00 → 06:00).')),
                ('allowed_late_minutes', models.PositiveIntegerField(default=0)),
                ('required_daily_hours', models.DecimalField(decimal_places=2, default=8.0, help_text='عدد الساعات المتوقعة في اليوم (مثلاً 8 ساعات).', max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_primary', models.BooleanField(default=True, help_text='هل هذا هو الشفت الأساسي للموظف خلال هذه الفترة؟')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='hr.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='hr.shift')),
            ],
            options={
                'ordering': ['employee__employee_code', 'start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='shift_assignment_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('on_leave', 'On Leave'), ('holiday', 'Holiday'), ('remote', 'Remote')], default='present', max_length=20)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, help_text='إجمالي ساعات العمل الفعلية في هذا اليوم.', max_digits=5)),
                ('is_overtime', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hr.employee')),
                ('shift', models.ForeignKey(blank=True, help_text='الشفت المتوقع لهذا اليوم إن وجد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='hr.shift')),
            ],
            options={
                'ordering': ['-date', 'employee__employee_code'],
                'indexes': [models.Index(fields=['date'], name='hr_attendan_date_07a719_idx'), models.Index(fields=['employee', 'date'], name='hr_attendan_employe_0dcc0e_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
