# Generated by Django 5.2.3 on 2025-11-21 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_shift_employeeshiftassignment_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم الدورة مثل: January 2026 Payroll', max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(help_text='1 = January, 12 = December')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('posted', 'Posted'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('total_employees', models.PositiveIntegerField(default=0)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, help_text='مجموع الرواتب الإجمالي قبل الخصومات.', max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, help_text='مجموع صافي الرواتب بعد الخصومات.', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='hr.company')),
            ],
            options={
                'ordering': ['-year', '-month', 'company__name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, help_text='مجموع البدلات (سكن، مواصلات، ...).', max_digits=12)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, help_text='بدل الساعات الإضافية.', max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, help_text='الخصومات (تأخير، غياب، تأمينات، ...).', max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, help_text='الراتب الإجمالي قبل الخصومات.', max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, help_text='الصافي بعد الخصومات.', max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_items', to='hr.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hr.payrollrun')),
            ],
            options={
                'ordering': ['payroll_run__year', 'payroll_run__month', 'employee__employee_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='payroll_period_end_after_start'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrun',
            unique_together={('company', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='payrollitem',
            index=models.Index(fields=['payroll_run', 'employee'], name='hr_payrolli_payroll_f7eb16_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollitem',
            unique_together={('payroll_run', 'employee')},
        ),
    ]
