# Generated by Django 5.2.3 on 2025-11-21 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_payrollrun_payrollitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان مختصر للسيرة مثل: Main CV 2025', max_length=255)),
                ('headline', models.CharField(blank=True, help_text='جملة مختصرة عن الموظف (Professional Headline).', max_length=255, null=True)),
                ('summary', models.TextField(blank=True, help_text='ملخص نصي لمحتوى السيرة (اختياري).', null=True)),
                ('file', models.FileField(blank=True, help_text='ملف السيرة الذاتية (PDF / DOCX...).', null=True, upload_to='resumes/%Y/%m/')),
                ('source_type', models.CharField(choices=[('uploaded', 'Uploaded'), ('imported', 'Imported/From External System'), ('ai_generated', 'AI Generated')], default='uploaded', max_length=20)),
                ('language', models.CharField(default='en', help_text='لغة السيرة مثل: en, ar, fr...', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('version', models.PositiveIntegerField(default=1, help_text='رقم الإصدار في حال حفظ عدة نسخ متتالية.')),
                ('skills_snapshot', models.TextField(blank=True, help_text='تمثيل JSON بسيط للمهارات وقت إنشاء السيرة (للأرشفة).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='hr.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('proof_type', models.CharField(choices=[('file', 'File'), ('link', 'Link'), ('text', 'Text / Description')], default='file', max_length=10)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='skill_proofs/%Y/%m/')),
                ('proof_link', models.URLField(blank=True, help_text='رابط لمشروع GitHub أو LinkedIn أو غيره.', null=True)),
                ('proof_text', models.TextField(blank=True, help_text='شرح نصي أو توصيف للإثبات.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_proofs', to='hr.employee')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_proofs', to='hr.resume')),
                ('verified_by', models.ForeignKey(blank=True, help_text='الموظف (غالباً HR أو Manager) الذي اعتمد هذا الإثبات.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_skill_proofs', to='hr.employee')),
            ],
            options={
                'ordering': ['-created_at', 'employee__employee_code', 'skill_name'],
            },
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['employee', 'status'], name='hr_resume_employe_694c70_idx'),
        ),
        migrations.AddIndex(
            model_name='skillproof',
            index=models.Index(fields=['employee', 'skill_name'], name='hr_skillpro_employe_b20c92_idx'),
        ),
        migrations.AddIndex(
            model_name='skillproof',
            index=models.Index(fields=['status'], name='hr_skillpro_status_680d85_idx'),
        ),
    ]
