# Generated by Django 5.2.3 on 2025-11-21 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_resume_skillproof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='full_time', max_length=20)),
                ('location', models.CharField(blank=True, help_text='مكان العمل (مدينة / دولة / Remote...).', max_length=255, null=True)),
                ('min_experience_years', models.PositiveIntegerField(default=0, help_text='الحد الأدنى لسنوات الخبرة المطلوبة.')),
                ('max_experience_years', models.PositiveIntegerField(blank=True, help_text='الحد الأقصى لسنوات الخبرة (اختياري).', null=True)),
                ('headcount', models.PositiveIntegerField(default=1, help_text='عدد الموظفين المطلوبين لهذا المتطلب.')),
                ('description', models.TextField(blank=True, help_text='وصف عام عن الوظيفة والمتطلبات الأخرى.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_requirements', to='hr.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='من قام بإضافة هذا المتطلب (غالباً HR / Manager).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_requirements', to='hr.employee')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_requirements', to='hr.department')),
                ('job_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_requirements', to='hr.joblevel')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_requirements', to='hr.jobtitle')),
            ],
            options={
                'ordering': ['company__name', 'department__name', 'job_title__title_name'],
                'unique_together': {('company', 'department', 'job_title', 'job_level', 'employment_type')},
            },
        ),
        migrations.CreateModel(
            name='JobRequirementSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True, help_text='هل المهارة أساسية (Must-have) أم اختيارية (Nice-to-have)؟')),
                ('weight', models.PositiveIntegerField(default=1, help_text='أهمية المهارة في تقييم المرشحين (1–10 مثلاً).')),
                ('notes', models.TextField(blank=True, null=True)),
                ('job_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='hr.jobrequirement')),
            ],
            options={
                'ordering': ['job_requirement', '-is_mandatory', '-weight', 'skill_name'],
                'unique_together': {('job_requirement', 'skill_name')},
            },
        ),
    ]
