# Generated by Django 5.2.3 on 2025-11-21 15:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_jobrequirement_jobrequirementskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('expiry_soon', 'Contract Expiry Soon'), ('expired', 'Contract Expired'), ('no_contract', 'No Active Contract'), ('probation_end', 'Probation Period Ending')], max_length=30)),
                ('alert_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField(help_text='نص التنبيه الذي سيتم عرضه للمستخدم أو المانجر.')),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, help_text='العقد المرتبط بهذا التنبيه إن وجد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='hr.employeecontract')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_alerts', to='hr.employee')),
            ],
            options={
                'ordering': ['-alert_date'],
                'indexes': [models.Index(fields=['employee', 'alert_type'], name='hr_contract_employe_3bd337_idx'), models.Index(fields=['is_read', 'is_resolved'], name='hr_contract_is_read_5fd0d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('unpaid', 'Unpaid Leave'), ('maternity', 'Maternity Leave'), ('emergency', 'Emergency Leave'), ('other', 'Other')], default='annual', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_half_day', models.BooleanField(default=False, help_text='إذا كانت الإجازة نصف يوم فقط.')),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='سبب إلغاء الطلب إن تم إلغاؤه.', null=True)),
                ('approver', models.ForeignKey(blank=True, help_text='الموظف (Manager/HR) الذي وافق/رفض الطلب.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to='hr.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='leave_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='ManpowerForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(help_text='1 = January, 12 = December')),
                ('current_headcount', models.PositiveIntegerField(default=0, help_text='عدد الموظفين الحالي في هذا القسم/الشركة.')),
                ('required_headcount', models.PositiveIntegerField(default=0, help_text='عدد الموظفين المطلوب حسب التنبؤ.')),
                ('gap', models.IntegerField(default=0, help_text='required - current (موجب = نقص، سالب = زيادة).')),
                ('ai_generated', models.BooleanField(default=True, help_text='هل هذه التوقعات مولدة بالـ AI أم مدخلة يدويًا.')),
                ('model_version', models.CharField(blank=True, help_text='رقم/اسم نسخة نموذج الذكاء الاصطناعي المستخدم.', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manpower_forecasts', to='hr.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manpower_forecasts', to='hr.department')),
            ],
            options={
                'ordering': ['-year', '-month', 'company__name', 'department__name'],
                'unique_together': {('company', 'department', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MyPayslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('net_salary', models.DecimalField(decimal_places=2, help_text='صافي الراتب لهذه القسيمة (نسخة محفوظة من PayrollItem).', max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('pdf_file', models.FileField(blank=True, help_text='نسخة PDF من قسيمة الراتب إن وجدت.', null=True, upload_to='payslips/%Y/%m/')),
                ('is_visible_to_employee', models.BooleanField(default=True, help_text='إذا كانت القسيمة ظاهرة للموظف في ESS أم مخفية.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr.employee')),
                ('payroll_item', models.OneToOneField(help_text='سطر الراتب المرتبط بهذه القسيمة.', on_delete=django.db.models.deletion.PROTECT, related_name='payslip', to='hr.payrollitem')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr.payrollrun')),
            ],
            options={
                'ordering': ['-year', '-month', 'employee__employee_code'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
