# Generated by Django 5.2.3 on 2025-11-21 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_contractalert_leaverequest_manpowerforecast_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('is_pinned', models.BooleanField(default=False, help_text='إذا true يظهر في الأعلى كخبر مهم.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='hr.company')),
            ],
            options={
                'ordering': ['-is_pinned', '-date', '-created_at'],
            },
        ),
    ]
