# Generated by Django 5.2.3 on 2025-12-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_companynews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='doc_type',
            field=models.CharField(choices=[('id', 'National ID/Passport'), ('contract', 'Contract'), ('certificate', 'Certificate'), ('cv', 'CV / Resume'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
