# Generated by Django 5.2.3 on 2025-12-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_alter_payrollitem_allowances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollitem',
            name='allowances',
            field=models.DecimalField(decimal_places=2, default=0, help_text='مجموع البدلات (سكن، مواصلات، ...).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollitem',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, help_text='الخصومات (تأخير، غياب، تأمينات، ...).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollitem',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='الراتب الإجمالي قبل الخصومات.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollitem',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='الصافي بعد الخصومات.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollitem',
            name='overtime_pay',
            field=models.DecimalField(decimal_places=2, default=0, help_text='بدل الساعات الإضافية.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='month',
            field=models.PositiveIntegerField(help_text='1 = January, 12 = December'),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='total_gross',
            field=models.DecimalField(decimal_places=2, default=0, help_text='مجموع الرواتب الإجمالي قبل الخصومات.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default=0, help_text='مجموع صافي الرواتب بعد الخصومات.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='file',
            field=models.FileField(blank=True, help_text='ملف PDF لكشف الراتب (اختياري).', null=True, upload_to='payslips/'),
        ),
    ]
