# Generated by Django 5.2.3 on 2025-12-04 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_alter_payrollitem_allowances_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('holiday', 'Holiday'), ('policy', 'Policy'), ('reminder', 'Reminder'), ('other', 'Other')], default='general', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='إذا كان True يظهر في أعلى القائمة.')),
                ('valid_from', models.DateField(blank=True, help_text='تاريخ بداية ظهور الإعلان (اختياري).', null=True)),
                ('valid_to', models.DateField(blank=True, help_text='تاريخ نهاية ظهور الإعلان (اختياري).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, help_text='إذا تُركت فارغة → الإعلان عام لكل الشركات.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='hr.company')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
