# Generated by Django 5.2.3 on 2025-12-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='performance_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Performance score (0–100) used in Manager dashboard.', max_digits=5),
        ),
    ]
