# Generated by Django 5.2.3 on 2025-12-25 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_skill_employeeskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='early_leave_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='hr.shift'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='employeeshiftassignment',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
    ]
