# Generated by Django 5.2.3 on 2025-12-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_attendancerecord_early_leave_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
