# Generated by Django 5.2.3 on 2025-11-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_full_name_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dashboard_mode',
            field=models.CharField(choices=[('smart', 'Smart Dashboard'), ('separate', 'Separate Dashboards')], default='smart', max_length=20),
        ),
    ]
